const paths: Paths = [
  { params: { theme: "abap", title: "ABAP", repo: "abap", icon: "/icons/used/pack-10/046-rum.svg", platform: ["all"] } },
  { params: { theme: "ableton-live", title: "Ableton Live", repo: "ableton-live", icon: "/icons/used/pack-5/039-flask.svg", platform: ["mac", "windows"] } },
  { params: { theme: "abricotine", title: "Abricotine", repo: "abricotine", icon: "/icons/used/pack-9/013-poison.svg", platform: ["all"] } },
  { params: { theme: "adminer", title: "Adminer", repo: "adminer", icon: "/icons/used/pack-8/005-moon.svg", platform: ["all"] } },
  { params: { theme: "adobe", title: "Adobe", repo: "adobe", icon: "/icons/used/pack-6/039-zombie.svg", platform: ["mac", "windows"], synonyms: ["photoshop", "illustrator"] } },
  { params: { theme: "aerc", title: "aerc", repo: "aerc", icon: "/icons/used/pack-4/010-centaur.svg", platform: ["all"] } },
  { params: { theme: "alacritty", title: "Alacritty", repo: "alacritty", icon: "/icons/used/pack-6/004-reaper.svg", platform: ["all"] } },
  { params: { theme: "albert", title: "Albert", repo: "albert", icon: "/icons/used/pack-7/011-food.svg", platform: ["linux"] } },
  { params: { theme: "alfred", title: "Alfred", repo: "alfred", icon: "/icons/used/pack-5/019-wizard hat.svg", platform: ["mac"] } },
  { params: { theme: "aliucord", title: "Aliucord", repo: "aliucord", icon: "/icons/used/pack-9/027-candy-cane.svg", platform: ["linux"] } },
  { params: { theme: "amfora", title: "Amfora", repo: "amfora", icon: "/icons/used/pack-9/011-bucket.svg", platform: ["all"] } },
  { params: { theme: "apollo", title: "Apollo", repo: "apollo", icon: "/icons/used/pack-8/001-space.svg", platform: ["mac"], synonyms: ["reddit"] } },
  { params: { theme: "archive-of-our-own", title: "Archive of Our Own", repo: "archive-of-our-own", icon: "/icons/used/pack-3/008-chest.svg", platform: ["all"] } },
  { params: { theme: "arduino-ide", title: "Arduino IDE", repo: "arduino-ide", icon: "/icons/used/pack-1/001-gallows.svg", platform: ["all"] } },
  { params: { theme: "arduino-pro-ide", title: "Arduino Pro IDE", repo: "arduino-pro-ide", icon: "/icons/used/pack-7/014-cauldron.svg", platform: ["all"] } },
  { params: { theme: "aseprite", title: "Aseprite", repo: "aseprite", icon: "/icons/used/pack-8/006-asteroid.svg", platform: ["all"] } },
  { params: { theme: "atom", title: "Atom", repo: "atom", icon: "/icons/used/pack-1/005-potion.svg", platform: ["all"] } },
  { params: { theme: "audacity", title: "Audacity", repo: "audacity", icon: "/icons/used/pack-3/020-magic-ball.svg", platform: ["windows"] } },
  { params: { theme: "auto-ao3-app", title: "AutoAO3App", repo: "auto-ao3-app", icon: "/icons/used/pack-5/028-magic hat.svg", platform: ["all"] } },
  { params: { theme: "b4x", title: "B4X", repo: "b4x", icon: "/icons/used/pack-7/038-broom.svg", platform: ["all"] } },
  { params: { theme: "bandcamp", title: "Bandcamp", repo: "bandcamp", icon: "/icons/used/pack-4/002-grapes.svg", platform: ["all"] } },
  { params: { theme: "base16", title: "Base16", repo: "base16-dracula-scheme", icon: "/icons/used/pack-6/030-graveyard.svg", platform: ["all"] } },
  { params: { theme: "bashtop", title: "Bashtop", repo: "bashtop", icon: "/icons/used/pack-7/044-monster.svg", platform: ["linux", "mac"] } },
  { params: { theme: "bbedit", title: "BBEdit", repo: "bbedit", icon: "/icons/used/pack-4/041-cyclops.svg", platform: ["mac"] } },
  { params: { theme: "beamer", title: "Beamer", repo: "beamer", icon: "/icons/used/pack-10/048-zombie.svg", platform: ["all"] } },
  { params: { theme: "bear", title: "Bear", repo: "bear", icon: "/icons/used/pack-1/008-tree.svg", platform: ["mac"] } },
  { params: { theme: "bemenu", title: "bemenu", repo: "bemenu", icon: "/icons/used/pack-7/027-gifts.svg", platform: ["linux", "mac"] } },
  { params: { theme: "betterdiscord", title: "BetterDiscord", repo: "betterdiscord", icon: "/icons/used/pack-2/030-game-controller.svg", platform: ["all"] } },
  { params: { theme: "beyond-compare-4", title: "Beyond Compare 4", repo: "beyond-compare-4", icon: "/icons/used/pack-10/050-scarecrow.svg", platform: ["all"] } },
  { params: { theme: "blender", title: "Blender", repo: "blender", icon: "/icons/used/pack-2/029-bomb.svg", platform: ["all"] } },
  { params: { theme: "blink-shell", title: "Blink Shell", repo: "blink-shell", icon: "/icons/used/pack-2/038-3d glasses.svg", platform: ["all"] } },
  { params: { theme: "blockbench", title: "Blockbench", repo: "blockbench", icon: "/icons/used/pack-2/034-video card.svg", platform: ["all"] } },
  { params: { theme: "bobthefish", title: "bobthefish", repo: "bobthefish", icon: "/icons/used/pack-10/001-witch.svg", platform: ["all"] } },
  { params: { theme: "brackets", title: "Brackets", repo: "brackets", icon: "/icons/used/pack-4/043-minotaur.svg", platform: ["all"] } },
  { params: { theme: "bspwm", title: "bspwm", repo: "bspwm", icon: "/icons/used/pack-6/022-candle.svg", platform: ["linux"] } },
  { params: { theme: "btcpay-server", title: "BTCPay Server", repo: "btcpay-server", icon: "/icons/used/pack-9/048-bat.svg", platform: ["all"] } },
  { params: { theme: "campfire", title: "Campfire", repo: "campfire", icon: "/icons/used/pack-7/020-lantern.svg", platform: ["all"] } },
  { params: { theme: "caprine-messenger", title: "Caprine Messenger", repo: "caprine-messenger", icon: "/icons/used/pack-10/033-crow.svg", platform: ["all"] } },
  { params: { theme: "cava", title: "Cava", repo: "cava", icon: "/icons/used/pack-3/038-rainbow.svg", platform: ["linux", "mac"] } },
  { params: { theme: "chrome", title: "Chrome", repo: "google-chrome", icon: "/icons/used/pack-10/007-pumpkins.svg", platform: ["all"], synonyms: ["google"] } },
  { params: { theme: "cider", title: "Cider", repo: "cider", icon: "/icons/used/pack-1/009-costume.svg", platform: ["all"] } },
  { params: { theme: "cli-visualizer", title: "Cli-Visualizer", repo: "cli-visualizer", icon: "/icons/used/pack-2/006-puzzle.svg", platform: ["all"] } },
  { params: { theme: "clone-hero", title: "Clone Hero", repo: "clone-hero", icon: "/icons/used/pack-2/036-game-controller.svg", platform: ["windows"] } },
  { params: { theme: "cmder", title: "Cmder", repo: "cmder", icon: "/icons/used/pack-1/006-night.svg", platform: ["windows"] } },
  { params: { theme: "coda", title: "Coda", repo: "coda", icon: "/icons/used/pack-1/013-lollipop.svg", platform: ["mac"] } },
  { params: { theme: "codeblocks", title: "Code::Blocks", repo: "codeblocks", icon: "/icons/used/pack-5/010-toolbox.svg", platform: ["all"] } },
  { params: { theme: "codepen", title: "CodePen", repo: "codepen", icon: "/icons/used/pack-9/049-magic-wand.svg", platform: ["all"] } },
  { params: { theme: "coderunner", title: "CodeRunner", repo: "coderunner", icon: "/icons/used/pack-10/024-cupcake.svg", platform: ["mac"] } },
  { params: { theme: "color-slurp", title: "ColorSlurp", repo: "color-slurp", icon: "/icons/used/pack-2/013-darts.svg", platform: ["mac"] } },
  { params: { theme: "colorls", title: "colorls", repo: "colorls", icon: "/icons/used/pack-2/026-building.svg", platform: ["all"] } },
  { params: { theme: "conemu", title: "ConEmu", repo: "conemu", icon: "/icons/used/pack-1/010-trident.svg", platform: ["windows"] } },
  { params: { theme: "copyq", title: "CopyQ", repo: "copyq", icon: "/icons/used/pack-8/009-robot.svg", platform: ["all"] } },
  { params: { theme: "coteditor", title: "CotEditor", repo: "coteditor", icon: "/icons/used/pack-1/026-mummy.svg", platform: ["mac"] } },
  { params: { theme: "couscous", title: "Couscous", repo: "couscous", icon: "/icons/used/pack-1/024-tombstone-1.svg", platform: ["all"] } },
  { params: { theme: "cryptowatch", title: "Cryptowatch", repo: "cryptowatch", icon: "/icons/used/pack-7/037-halloween.svg", platform: ["all"] } },
  { params: { theme: "delphi", title: "Delphi", repo: "delphi", icon: "/icons/used/pack-9/032-tree.svg", platform: ["all"] } },
  { params: { theme: "dev-cpp", title: "Dev-C++", repo: "dev-cpp", icon: "/icons/used/pack-9/021-scream.svg", platform: ["windows"] } },
  { params: { theme: "dircolors", title: ".dircolors", repo: "dircolors", icon: "/icons/used/pack-9/037-paper-bag.svg", platform: ["linux"] } },
  { params: { theme: "discordbotmaker", title: "Discord Bot Maker", repo: "discordbotmaker", icon: "/icons/used/pack-10/041-potion.svg", platform: ["windows"] } },
  { params: { theme: "discourse", title: "Discourse", repo: "discourse", icon: "/icons/used/pack-7/032-bat.svg", platform: ["all"] } },
  { params: { theme: "ditto", title: "Ditto", repo: "ditto", icon: "/icons/used/pack-7/023-balloons.svg", platform: ["windows"] } },
  { params: { theme: "dmenu", title: "Dmenu", repo: "dmenu", icon: "/icons/used/pack-1/012-bag.svg", platform: ["linux"] } },
  { params: { theme: "doom-emacs", title: "DOOM Emacs", repo: "doom-emacs", icon: "/icons/used/pack-7/007-living-dead.svg", platform: ["all"] } },
  { params: { theme: "drafts", title: "Drafts", repo: "drafts", icon: "/icons/used/pack-5/006-treasure-chest.svg", platform: ["mac"] } },
  { params: { theme: "duckduckgo", title: "DuckDuckGo", repo: "duckduckgo", icon: "/icons/used/pack-1/002-coffin.svg", platform: ["all"] } },
  { params: { theme: "dunst", title: "Dunst", repo: "dunst", icon: "/icons/used/pack-7/033-trident.svg", platform: ["all"] } },
  { params: { theme: "dwarf-fortress", title: "Dwarf Fortress", repo: "dwarf-fortress", icon: "/icons/used/pack-10/038-dwarf.svg", platform: ["all"] } },
  { params: { theme: "dyalog", title: "Dyalog APL", repo: "dyalog", icon: "/icons/used/pack-4/027-flag.svg", platform: ["windows"] } },
  { params: { theme: "eclipse", title: "Eclipse", repo: "eclipse", icon: "/icons/used/pack-7/008-full moon.svg", platform: ["all"] } },
  { params: { theme: "editplus", title: "Editplus", repo: "editplus", icon: "/icons/used/pack-1/023-bones.svg", platform: ["windows"] } },
  { params: { theme: "em-client", title: "eM Client", repo: "em-client", icon: "/icons/used/pack-9/009-broomstick.svg", platform: ["mac", "windows"] } },
  { params: { theme: "emacs", title: "Emacs", repo: "emacs", icon: "/icons/used/pack-1/018-devil.svg", platform: ["all"] } },
  { params: { theme: "everythingtoolbar", title: "EverythingToolbar", repo: "everythingtoolbar", icon: "/icons/used/pack-7/019-mask.svg", platform: ["windows"] } },
  { params: { theme: "exa", title: "exa", repo: "exa", icon: "/icons/used/pack-10/014-vampire.svg", platform: ["linux, mac"] } },
  { params: { theme: "facebook-messenger", title: "Facebook Messenger", repo: "fb-messenger", icon: "/icons/used/pack-3/041-scroll.svg", platform: ["all"] } },
  { params: { theme: "fedilab", title: "Fedilab", repo: "fedilab", icon: "/icons/used/pack-8/013-capsule.svg", platform: ["all"] } },
  { params: { theme: "fig", title: "Fig", repo: "fig", icon: "/icons/used/pack-9/026-castle.svg", platform: ["mac"] } },
  { params: { theme: "figma", title: "Figma", repo: "figma", icon: "/icons/used/pack-4/044-werewolf.svg", platform: ["all"] } },
  { params: { theme: "files", title: "Files", repo: "files", icon: "/icons/used/pack-10/016-pumpkin.svg", platform: ["windows"] } },
  { params: { theme: "firefox", title: "Firefox", repo: "firefox", icon: "/icons/used/pack-1/028-finger.svg", platform: ["all"] } },
  { params: { theme: "fish", title: "Fish", repo: "fish", icon: "/icons/used/pack-1/011-poison.svg", platform: ["all"] } },
  { params: { theme: "fl-studio-21", title: "FL Studio 21", repo: "fl-studio-21", icon: "/icons/used/pack-4/022-harp.svg", platform: ["all"] } },
  { params: { theme: "flarum", title: "Flarum", repo: "flarum", icon: "/icons/used/pack-10/030-lantern.svg", platform: ["all"] } },
  { params: { theme: "florisboard", title: "FlorisBoard", repo: "florisboard", icon: "/icons/used/pack-9/024-candle.svg", platform: ["all"] } },
  { params: { theme: "flowlab", title: "Flowlab", repo: "flowlab", icon: "/icons/used/pack-2/007-mobile-game.svg", platform: ["all"] } },
  { params: { theme: "fluent-terminal", title: "Fluent Terminal", repo: "fluent-terminal", icon: "/icons/used/pack-1/049-bats.svg", platform: ["windows"] } },
  { params: { theme: "fman", title: "fman", repo: "fman", icon: "/icons/used/pack-8/028-alien.svg", platform: ["all"] } },
  { params: { theme: "foot-terminal", title: "foot", repo: "foot", icon: "/icons/used/pack-6/042-corpse.svg", platform: ["linux"] } },
  { params: { theme: "forklift", title: "ForkLift", repo: "forklift", icon: "/icons/used/pack-13/023-cemetery.svg", platform: ["mac"] } },
  { params: { theme: "freecad", title: "FreeCAD", repo: "freecad", icon: "/icons/used/pack-2/018-jenga.svg", platform: ["all"] } },
  { params: { theme: "freetube", title: "FreeTube", repo: "freetube", icon: "/icons/used/pack-8/023-monkey.svg", platform: ["all"] } },
  { params: { theme: "funkwhale", title: "Funkwhale", repo: "funkwhale", icon: "/icons/used/pack-9/044-scythe.svg", platform: ["all"] } },
  { params: { theme: "fuzzel", title: "fuzzel", repo: "fuzzel", icon: "/icons/used/pack-11/046-robot.svg", platform: ["linux"] } },
  { params: { theme: "fzf", title: "FZF", repo: "fzf", icon: "/icons/used/pack-10/027-eyeball.svg", platform: ["all"] } },
  { params: { theme: "gajim", title: "Gajim", repo: "gajim", icon: "/icons/used/pack-10/005-bat.svg", platform: ["all"] } },
  { params: { theme: "gamemaker-studio", title: "GameMaker Studio", repo: "gamemaker-studio", icon: "/icons/used/pack-1/031-serial-killer.svg", platform: ["all"] } },
  { params: { theme: "gamepad-viewer", title: "Gamepad Viewer", repo: "gamepad-viewer", icon: "/icons/used/pack-2/010-game-controller.svg", platform: ["all"] } },
  { params: { theme: "geany", title: "Geany", repo: "geany", icon: "/icons/used/pack-3/009-crystal-ball.svg", platform: ["all"] } },
  { params: { theme: "gedit", title: "Gedit", repo: "gedit", icon: "/icons/used/pack-1/036-spellbook.svg", platform: ["all"] } },
  { params: { theme: "ggplot2", title: "ggplot2", repo: "ggplot2", icon: "/icons/used/pack-9/018-lollipop.svg", platform: ["all"] } },
  { params: { theme: "ghostwriter", title: "ghostwriter", repo: "ghostwriter", icon: "/icons/used/pack-10/012-ghost.svg", platform: ["windows", "linux"] } },
  { params: { theme: "gimp", title: "GIMP", repo: "gimp", icon: "/icons/used/pack-5/001-magic-wand.svg", platform: ["linux"] } },
  { params: { theme: "git", title: "Git", repo: "git", icon: "/icons/used/pack-3/003-book.svg", platform: ["all"] } },
  { params: { theme: "github-pages", title: "GitHub Pages", repo: "gh-pages", icon: "/icons/used/pack-1/037-candies.svg", platform: ["all"] } },
  { params: { theme: "github", title: "GitHub", repo: "github", icon: "/icons/used/pack-7/045-cat.svg", platform: ["all"] } },
  { params: { theme: "gitk", title: "Gitk", repo: "gitk", icon: "/icons/used/pack-5/020-saw.svg", platform: ["all"] } },
  { params: { theme: "gitkraken", title: "GitKraken", repo: "gitkraken", icon: "/icons/used/pack-9/033-bug.svg", platform: ["all"] } },
  { params: { theme: "gitlab", title: "GitLab", repo: "gitlab", icon: "/icons/used/pack-10/009-cat.svg", platform: ["all"] } },
  { params: { theme: "gmk", title: "GMK", repo: "gmk", icon: "/icons/used/pack-4/016-axe.svg", platform: ["all"] } },
  { params: { theme: "gnome-terminal", title: "Gnome Terminal", repo: "gnome-terminal", icon: "/icons/used/pack-6/040-crow.svg", platform: ["linux"] } },
  { params: { theme: "godot", title: "Godot", repo: "godot", icon: "/icons/used/pack-7/024-skeleton.svg", platform: ["all"] } },
  { params: { theme: "grub", title: "GRUB", repo: "grub", icon: "/icons/used/pack-9/045-spider.svg", platform: ["linux"] } },
  { params: { theme: "gtk", title: "GTK", repo: "gtk", icon: "/icons/used/pack-5/008-wizard.svg", platform: ["linux"] } },
  { params: { theme: "hacker-news", title: "Hacker News", repo: "hacker-news", icon: "/icons/used/pack-8/021-satellite.svg", platform: ["all"] } },
  { params: { theme: "harpy-for-twitter", title: "Harpy for Twitter", repo: "harpy-for-twitter", icon: "/icons/used/pack-4/008-griffin.svg", platform: ["all"] } },
  { params: { theme: "highlightjs", title: "Highlight.js", repo: "highlightjs", icon: "/icons/used/pack-6/032-graveyard.svg", platform: ["all"] } },
  { params: { theme: "homer", title: "Homer", repo: "homer", icon: "/icons/used/pack-10/029-candies.svg", platform: ["all"] } },
  { params: { theme: "hyper", title: "Hyper", repo: "hyper", icon: "/icons/used/pack-1/025-candle-1.svg", platform: ["all"] } },
  { params: { theme: "hyprland", title: "Hyprland", repo: "hyprland", icon: "/icons/used/pack-13/015-eye ball.svg", platform: ["linux"] } },
  { params: { theme: "i3", title: "i3", repo: "i3", icon: "/icons/used/pack-1/016-candies-1.svg", platform: ["linux"] } },
  { params: { theme: "i3lock-color", title: "i3lock-color", repo: "i3lock-color", icon: "/icons/used/pack-5/022-padlock.svg", platform: ["linux"] } },
  { params: { theme: "ida", title: "IDA Pro", repo: "ida", icon: "/icons/used/pack-7/018-cleaver.svg", platform: ["all"] } },
  { params: { theme: "idle", title: "IDLE", repo: "idle", icon: "/icons/used/pack-5/042-handcuffs.svg", platform: ["all"] } },
  { params: { theme: "imageglass", title: "ImageGlass", repo: "imageglass", icon: "/icons/used/pack-10/032-crystal.svg", platform: ["windows"] } },
  { params: { theme: "infinity-for-reddit", title: "Infinity for Reddit", repo: "infinity-for-reddit", icon: "/icons/used/pack-8/016-galaxy.svg", platform: ["all"] } },
  { params: { theme: "inkscape", title: "Inkscape", repo: "inkscape", icon: "/icons/used/pack-7/030-skull.svg", platform: ["all"] } },
  { params: { theme: "insomnia", title: "Insomnia", repo: "insomnia", icon: "/icons/used/pack-1/043-scythe.svg", platform: ["all"] } },
  { params: { theme: "ish", title: "iSH", repo: "ish", icon: "/icons/used/pack-6/031-broken.svg", platform: ["all"] } },
  { params: { theme: "iterm", title: "iTerm", repo: "iterm", icon: "/icons/used/pack-7/042-haunted house.svg", platform: ["mac"] } },
  { params: { theme: "itfy", title: "ITFY", repo: "itfy", icon: "/icons/used/pack-10/040-skeleton.svg", platform: ["all"] } },
  { params: { theme: "jabref", title: "Jabref", repo: "jabref", icon: "/icons/used/pack-1/022-witch.svg", platform: ["all"] } },
  { params: { theme: "javadoc", title: "Javadoc", repo: "javadoc", icon: "/icons/used/pack-2/043-sword.svg", platform: ["all"] } },
  { params: { theme: "jdownloader2", title: "JDownloader2", repo: "jdownloader2", icon: "/icons/used/pack-3/001-fairy-dust.svg", platform: ["all"] } },
  { params: { theme: "jetbrains", title: "JetBrains", repo: "jetbrains", icon: "/icons/used/pack-1/046-zombie.svg", platform: ["all"], synonyms: ["intellij", "pycharm", "webstorm", "phpstorm", "rider", "clion", "datagrip", "rubymine", "appcode", "goland"] } },
  { params: { theme: "jgrasp", title: "jGrasp", repo: "jgrasp", icon: "/icons/used/pack-1/007-guillotine.svg", platform: ["all"] } },
  { params: { theme: "joplin", title: "Joplin", repo: "joplin", icon: "/icons/used/pack-10/006-coffin.svg", platform: ["all"] } },
  { params: { theme: "jupyter-notebook", title: "Jupyter Notebook", repo: "jupyter-notebook", icon: "/icons/used/pack-11/037-alien.svg", platform: ["all"] } },
  { params: { theme: "jupyterlab", title: "JupyterLab", repo: "jupyterlab", icon: "/icons/used/pack-6/012-candles.svg", platform: ["all"] } },
  { params: { theme: "kakoune", title: "Kakoune", repo: "kakoune", icon: "/icons/used/pack-1/033-black-cat.svg", platform: ["linux"] } },
  { params: { theme: "kanbanflow", title: "KanbanFlow", repo: "kanbanflow", icon: "/icons/used/pack-9/038-candy-corn.svg", platform: ["all"] } },
  { params: { theme: "kate", title: "Kate", repo: "kate", icon: "/icons/used/pack-5/033-smoke.svg", platform: ["all"] } },
  { params: { theme: "kdiff3", title: "KDiff3", repo: "kdiff3", icon: "/icons/used/pack-10/047-gate.svg", platform: ["all"] } },
  { params: { theme: "keypirinha", title: "Keypirinha", repo: "keypirinha", icon: "/icons/used/pack-1/004-fear.svg", platform: ["windows"] } },
  { params: { theme: "kicad", title: "KiCad", repo: "kicad", icon: "/icons/used/pack-7/015-witch-hat.svg", platform: ["all"] } },
  { params: { theme: "kitty", title: "Kitty", repo: "kitty", icon: "/icons/used/pack-1/015-makeup.svg", platform: ["all"] } },
  { params: { theme: "konsole", title: "Konsole", repo: "konsole", icon: "/icons/used/pack-3/035-potion-1.svg", platform: ["linux"] } },
  { params: { theme: "kristall", title: "Kristall", repo: "kristall", icon: "/icons/used/pack-5/018-magic wand.svg", platform: ["all"] } },
  { params: { theme: "krita", title: "Krita", repo: "krita", icon: "/icons/used/pack-10/028-poison.svg", platform: ["all"] } },
  { params: { theme: "kurozora", title: "Kurozora", repo: "kurozora", icon: "/icons/used/pack-13/003-pumpkin.svg", platform: ["all"] } },
  { params: { theme: "latex", title: "LaTeX", repo: "latex", icon: "/icons/used/pack-9/023-pumpkin.svg", platform: ["all"] } },
  { params: { theme: "leftwm", title: "leftwm", repo: "leftwm", icon: "/icons/used/pack-5/021-magic trick.svg", platform: ["linux"] } },
  { params: { theme: "libreddit", title: "Libreddit", repo: "libreddit", icon: "/icons/used/pack-4/025-amphora.svg", platform: ["all"] } },
  { params: { theme: "libreoffice", title: "LibreOffice", repo: "libreoffice", icon: "/icons/used/pack-7/010-spellbook.svg", platform: ["all"] } },
  { params: { theme: "light-table", title: "Light Table", repo: "light-table", icon: "/icons/used/pack-1/050-pumpkin.svg", platform: ["all"] } },
  { params: { theme: "lightpaper", title: "LightPaper", repo: "lightpaper", icon: "/icons/used/pack-5/030-voodoo.svg", platform: ["mac"] } },
  { params: { theme: "limechat", title: "LimeChat", repo: "limechat", icon: "/icons/used/pack-3/016-fire.svg", platform: ["mac"] } },
  { params: { theme: "linear", title: "Linear", repo: "linear", icon: "/icons/used/pack-8/015-planet.svg", platform: ["all"] } },
  { params: { theme: "liteide", title: "LiteIDE", repo: "liteide", icon: "/icons/used/pack-7/041-spider.svg", platform: ["all"] } },
  { params: { theme: "logseq", title: "Logseq", repo: "logseq", icon: "/icons/used/pack-8/032-constellation.svg", platform: ["all"] } },
  { params: { theme: "lsd", title: "lsd", repo: "lsd", icon: "/icons/used/pack-13/025-fairy.svg", platform: ["all"] } },
  { params: { theme: "ltspice", title: "LTSpice", repo: "ltspice", icon: "/icons/used/pack-7/048-coffin.svg", platform: ["all"] } },
  { params: { theme: "lxterminal", title: "LXTerminal", repo: "lxterminal", icon: "/icons/used/pack-10/039-balloon.svg", platform: ["linux"] } },
  { params: { theme: "macdown", title: "MacDown", repo: "macdown", icon: "/icons/used/pack-1/042-candle.svg", platform: ["mac"] } },
  { params: { theme: "macos-color-picker", title: "macOS Color Picker", repo: "macos-color-picker", icon: "/icons/used/pack-3/010-crystal.svg", platform: ["mac"] } },
  { params: { theme: "mailspring", title: "Mailspring", repo: "mailspring", icon: "/icons/used/pack-7/009-owl.svg", platform: ["all"] } },
  { params: { theme: "makehuman", title: "Makehuman", repo: "makehuman", icon: "/icons/used/pack-3/026-spell.svg", platform: ["all"] } },
  { params: { theme: "mako", title: "Mako", repo: "mako", icon: "/icons/used/pack-10/037-ghost-1.svg", platform: ["linux"] } },
  { params: { theme: "man-pages", title: "man-pages", repo: "man-pages", icon: "/icons/used/pack-10/043-prisoner.svg", platform: ["linux"] } },
  { params: { theme: "marp", title: "Marp", repo: "marp", icon: "/icons/used/pack-7/036-party.svg", platform: ["all"] } },
  { params: { theme: "matlab", title: "MATLAB", repo: "matlab", icon: "/icons/used/pack-7/049-grim-reaper.svg", platform: ["all"] } },
  { params: { theme: "matplotlib", title: "Matplotlib", repo: "matplotlib", icon: "/icons/used/pack-7/021-frankenstein.svg", platform: ["all"] } },
  { params: { theme: "mattermost", title: "Mattermost", repo: "mattermost", icon: "/icons/used/pack-1/019-spider.svg", platform: ["all"] } },
  { params: { theme: "metaeditor", title: "MetaEditor", repo: "metaeditor", icon: "/icons/used/pack-10/035-gift.svg", platform: ["windows"] } },
  { params: { theme: "metatrader5", title: "MetaTrader 5", repo: "metatrader5", icon: "/icons/used/pack-9/036-witch-hat.svg", platform: ["all"] } },
  { params: { theme: "micro", title: "Micro", repo: "micro", icon: "/icons/used/pack-3/019-lantern.svg", platform: ["all"] } },
  { params: { theme: "midnight-commander", title: "Midnight Commander", repo: "midnight-commander", icon: "/icons/used/pack-3/030-moon.svg", platform: ["all"] } },
  { params: { theme: "mindnode", title: "MindNode", repo: "mindnode", icon: "/icons/used/pack-5/007-magic-mirror.svg", platform: ["mac"] } },
  { params: { theme: "minecraft", title: "Minecraft", repo: "minecraft", icon: "/icons/used/pack-2/045-computer game.svg", platform: ["all"] } },
  { params: { theme: "mintty", title: "Mintty", repo: "mintty", icon: "/icons/used/pack-1/014-voodoo-doll.svg", platform: ["windows"] } },
  { params: { theme: "misskey", title: "Misskey", repo: "misskey", icon: "/icons/used/pack-4/009-hephaestus-1.svg", platform: ["all"] } },
  { params: { theme: "mixplorer", title: "MiXplorer", repo: "mixplorer", icon: "/icons/used/pack-9/029-spellbook.svg", platform: ["linux"] } },
  { params: { theme: "mkdocs", title: "MkDocs", repo: "mkdocs", icon: "/icons/used/pack-13/043-bible.svg", platform: ["all"] } },
  { params: { theme: "mobaxterm", title: "MobaXterm", repo: "mobaxterm", icon: "/icons/used/pack-3/042-skull.svg", platform: ["windows"] } },
  { params: { theme: "monkeytype", title: "Monkeytype", repo: "monkeytype", icon: "/icons/used/pack-10/004-mummy.svg", platform: ["all"] } },
  { params: { theme: "monodevelop", title: "MonoDevelop", repo: "monodevelop", icon: "/icons/used/pack-1/027-hand.svg", platform: ["all"] } },
  { params: { theme: "mousepad", title: "Mousepad", repo: "mousepad", icon: "/icons/used/pack-2/022-mouse.svg", platform: ["linux"] } },
  { params: { theme: "musicbee", title: "MusicBee", repo: "musicbee", icon: "/icons/used/pack-3/022-magic.svg", platform: ["all"] } },
  { params: { theme: "musikcube", title: "musikcube", repo: "musikcube", icon: "/icons/used/pack-9/020-bomb.svg", platform: ["all"] } },
  { params: { theme: "mutt", title: "Mutt", repo: "mutt", icon: "/icons/used/pack-3/045-tree.svg", platform: ["all"] } },
  { params: { theme: "mysql-workbench", title: "MySQL Workbench", repo: "mysql-workbench", icon: "/icons/used/pack-9/040-scarecrow.svg", platform: ["all"] } },
  { params: { theme: "ncspot", title: "ncspot", repo: "ncspot", icon: "/icons/used/pack-7/039-tombstone.svg", platform: ["all"] } },
  { params: { theme: "netbeans", title: "Netbeans", repo: "netbeans", icon: "/icons/used/pack-7/017-scarecrow.svg", platform: ["all"] } },
  { params: { theme: "new-tabs", title: "New Tabs", repo: "new-tabs", icon: "/icons/used/pack-5/017-magician hat.svg", platform: ["all"] } },
  { params: { theme: "newsboat", title: "Newsboat", repo: "newsboat", icon: "/icons/used/pack-7/047-vampire.svg", platform: ["all"] } },
  { params: { theme: "newterm2", title: "NewTerm2", repo: "NewTerm2", icon: "/icons/used/pack-7/026-mask.svg", platform: ["all"] } },
  { params: { theme: "nextcloud", title: "Nextcloud", repo: "nextcloud", icon: "/icons/used/pack-2/044-podium.svg", platform: ["all"] } },
  { params: { theme: "ngenuity", title: "HyperX NGNUITY", repo: "ngenuity", icon: "/icons/used/pack-3/018-key.svg", platform: ["all"] } },
  { params: { theme: "nitter", title: "Nitter", repo: "nitter", icon: "/icons/used/pack-4/007-owl.svg", platform: ["all"] } },
  { params: { theme: "node-console", title: "Node Console", repo: "node-console", icon: "/icons/used/pack-9/025-owl.svg", platform: ["all"] } },
  { params: { theme: "noir", title: "Noir", repo: "noir", icon: "/icons/used/pack-8/036-eclipse.svg", platform: ["mac"] } },
  { params: { theme: "notepad-plus-plus", title: "Notepad++", repo: "notepad-plus-plus", icon: "/icons/used/pack-7/002-ghosts.svg", platform: ["windows"] } },
  { params: { theme: "nova-launcher", title: "Nova Launcher", repo: "nova-launcher", icon: "/icons/used/pack-9/003-witch.svg", platform: ["linux"] } },
  { params: { theme: "nova", title: "Nova", repo: "nova", icon: "/icons/used/pack-8/037-meteor.svg", platform: ["mac"] } },
  { params: { theme: "novel-writer", title: "novelWriter", repo: "novel-writer", icon: "/icons/used/pack-5/043-stage.svg", platform: ["all"] } },
  { params: { theme: "nylas-n1", title: "Nylas N1", repo: "nylas-n1", icon: "/icons/used/pack-5/045-hourglass.svg", platform: ["all"] } },
  { params: { theme: "nyxt", title: "Nyxt", repo: "nyxt", icon: "/icons/used/pack-9/047-cauldron.svg", platform: ["linux", "mac"] } },
  { params: { theme: "obsidian", title: "Obsidian", repo: "obsidian", icon: "/icons/used/pack-5/036-gemstone.svg", platform: ["all"] } },
  { params: { theme: "oh-my-posh", title: "Oh My Posh", repo: "oh-my-posh", icon: "/icons/used/pack-7/046-zombie.svg", platform: ["all"] } },
  { params: { theme: "omglol", title: "omg.lol", repo: "omglol", icon: "/icons/used/pack-4/001-zeus.svg", platform: ["all"] } },
  { params: { theme: "openbox", title: "Openbox", repo: "openbox", icon: "/icons/used/pack-2/041-box.svg", platform: ["linux"] } },
  { params: { theme: "oracle-sql-developer", title: "Oracle SQL Developer", repo: "oracle-sql-developer", icon: "/icons/used/pack-1/029-werewolf.svg", platform: ["all"] } },
  { params: { theme: "pandoc", title: "Pandoc", repo: "pandoc", icon: "/icons/used/pack-9/035-black-cat.svg", platform: ["all"] } },
  { params: { theme: "pantheon-terminal", title: "Pantheon Terminal", repo: "pantheon-terminal", icon: "/icons/used/pack-9/041-torch.svg", platform: ["linux"] } },
  { params: { theme: "passky", title: "Passky", repo: "passky", icon: "/icons/used/pack-9/012-skull.svg", platform: ["all"] } },
  { params: { theme: "peacock-extension", title: "Peacock Extension", repo: "peacock-extension", icon: "/icons/used/pack-4/005-dove.svg", platform: ["all"] } },
  { params: { theme: "plank", title: "Plank", repo: "plank", icon: "/icons/used/pack-4/029-trireme.svg", platform: ["all"] } },
  { params: { theme: "plsql-developer", title: "PL/SQL Developer", repo: "plsql-developer", icon: "/icons/used/pack-10/026-pirate.svg", platform: ["all"] } },
  { params: { theme: "plymouth", title: "Plymouth", repo: "plymouth", icon: "/icons/used/pack-13/039-dessert.svg", platform: ["linux"] } },
  { params: { theme: "polymc", title: "PolyMC", repo: "polymc", icon: "/icons/used/pack-2/024-hearts.svg", platform: ["all"] } },
  { params: { theme: "postbox", title: "Postbox", repo: "postbox", icon: "/icons/used/pack-4/038-hermes-2.svg", platform: ["all"] } },
  { params: { theme: "powerlevel10k", title: "Powerlevel10k", repo: "powerlevel10k", icon: "/icons/used/pack-9/016-hook.svg", platform: ["all"] } },
  { params: { theme: "powershell", title: "PowerShell", repo: "powershell", icon: "/icons/used/pack-5/046-magic trick.svg", platform: ["all"], synonyms: ["cmd.exe"] } },
  { params: { theme: "prism", title: "Prism", repo: "prism", icon: "/icons/used/pack-3/034-pot.svg", platform: ["all"] } },
  { params: { theme: "psychopy", title: "PsychoPy", repo: "psychopy", icon: "/icons/used/pack-10/049-serial-killer.svg", platform: ["all"] } },
  { params: { theme: "pygments", title: "Pygments", repo: "pygments", icon: "/icons/used/pack-1/039-ghost.svg", platform: ["all"] } },
  { params: { theme: "pythonista", title: "Pythonista", repo: "pythonista", icon: "/icons/used/pack-6/048-grave.svg", platform: ["mac"] } },
  { params: { theme: "pywal", title: "Pywal", repo: "pywal", icon: "/icons/used/pack-5/005-magic-broom.svg", platform: ["all"] } },
  { params: { theme: "qbittorrent", title: "QBittorrent", repo: "qbittorrent", icon: "/icons/used/pack-10/010-candle.svg", platform: ["all"] } },
  { params: { theme: "qt5", title: "qt5", repo: "qt5", icon: "/icons/used/pack-7/043-candles.svg", platform: ["all"] } },
  { params: { theme: "qtcreator", title: "Qt Creator", repo: "qtcreator", icon: "/icons/used/pack-5/024-cauldron.svg", platform: ["all"] } },
  { params: { theme: "qterminal", title: "Qterminal", repo: "qterminal", icon: "/icons/used/pack-9/046-muffin.svg", platform: ["all"] } },
  { params: { theme: "quassel", title: "Quassel", repo: "quassel", icon: "/icons/used/pack-4/046-evil.svg", platform: ["all"] } },
  { params: { theme: "quiver", title: "Quiver", repo: "quiver", icon: "/icons/used/pack-5/041-guillotine.svg", platform: ["mac"] } },
  { params: { theme: "qutebrowser", title: "Qutebrowser", repo: "qutebrowser", icon: "/icons/used/pack-5/015-box.svg", platform: ["all"] } },
  { params: { theme: "ranger", title: "ranger", repo: "ranger", icon: "/icons/used/pack-9/019-brain.svg", platform: ["all"] } },
  { params: { theme: "renoise", title: "ReNoise", repo: "renoise", icon: "/icons/used/pack-8/047-computer.svg", platform: ["all"] } },
  { params: { theme: "replugged", title: "Replugged", repo: "replugged", icon: "/icons/used/pack-2/025-tetris.svg", platform: ["all"] } },
  { params: { theme: "revolt", title: "Revolt", repo: "revolt", icon: "/icons/used/pack-9/030-coffin.svg", platform: ["all"] } },
  { params: { theme: "revolution-irc", title: "Revolution IRC", repo: "revolution-irc", icon: "/icons/used/pack-9/008-trident.svg", platform: ["linux"] } },
  { params: { theme: "ripcord", title: "Ripcord", repo: "ripcord", icon: "/icons/used/pack-10/042-knife.svg", platform: ["all"] } },
  { params: { theme: "roam-research", title: "Roam Research", repo: "roam-research", icon: "/icons/used/pack-5/050-circle.svg", platform: ["all"] } },
  { params: { theme: "rofi", title: "rofi", repo: "rofi", icon: "/icons/used/pack-7/028-lollipop.svg", platform: ["linux"] } },
  { params: { theme: "rstudio", title: "RStudio", repo: "rstudio", icon: "/icons/used/pack-9/014-living-dead.svg", platform: ["all"] } },
  { params: { theme: "runjs", title: "RunJs", repo: "runjs", icon: "/icons/used/pack-4/030-chariot.svg", platform: ["all"] } },
  { params: { theme: "sandpack", title: "Sandpack", repo: "sandpack", icon: "/icons/used/pack-3/007-castle.svg", platform: ["all"] } },
  { params: { theme: "scrivener", title: "Scrivener", repo: "scrivener", icon: "/icons/used/pack-3/015-feather.svg", platform: ["all"] } },
  { params: { theme: "sequel-ace", title: "Sequel Ace", repo: "sequel-ace", icon: "/icons/used/pack-9/001-moon.svg", platform: ["mac"] } },
  { params: { theme: "sequel-pro", title: "Sequel Pro", repo: "sequel-pro", icon: "/icons/used/pack-5/012-spell book.svg", platform: ["mac"] } },
  { params: { theme: "serenityos", title: "SerenityOS", repo: "serenityos", icon: "/icons/used/pack-8/014-galaxy.svg", platform: ["linux"] } },
  { params: { theme: "sidenotes", title: "SideNotes", repo: "sidenotes", icon: "/icons/used/pack-9/050-knife.svg", platform: ["mac"] } },
  { params: { theme: "sioyek", title: "Sioyek", repo: "sioyek", icon: "/icons/used/pack-5/023-mask.svg", platform: ["all"] } },
  { params: { theme: "sketch", title: "Sketch", repo: "sketch", icon: "/icons/used/pack-3/025-magic-wand-1.svg", platform: ["all"] } },
  { params: { theme: "slack", title: "Slack", repo: "slack", icon: "/icons/used/pack-1/047-cleaver.svg", platform: ["all"] } },
  { params: { theme: "snippetslab", title: "SnippetsLab", repo: "snippetslab", icon: "/icons/used/pack-5/037-powder.svg", platform: ["mac"] } },
  { params: { theme: "solidworks", title: "SolidWorks", repo: "solidworks", icon: "/icons/used/pack-10/044-monster-1.svg", platform: ["windows"] } },
  { params: { theme: "spacemacs", title: "Spacemacs", repo: "spacemacs", icon: "/icons/used/pack-8/018-planet.svg", platform: ["all"] } },
  { params: { theme: "speedcrunch", title: "SpeedCrunch", repo: "speedcrunch", icon: "/icons/used/pack-2/005-slot machine.svg", platform: ["all"] } },
  { params: { theme: "spicetify", title: "Spicetify", repo: "spicetify", icon: "/icons/used/pack-4/020-mandolin.svg", platform: ["all"] } },
  { params: { theme: "spotify-tui", title: "Spotify TUI", repo: "spotify-tui", icon: "/icons/used/pack-7/031-sweets.svg", platform: ["all"] } },
  { params: { theme: "spyder-ide", title: "Spyder IDE", repo: "spyder-ide", icon: "/icons/used/pack-10/002-spider.svg", platform: ["all"] } },
  { params: { theme: "st", title: "st", repo: "st", icon: "/icons/used/pack-13/042-halloween.svg", platform: ["linux"] } },
  { params: { theme: "stackoverflow", title: "StackOverflow", repo: "stackoverflow", icon: "/icons/used/pack-5/026-candlestick.svg", platform: ["all"] } },
  { params: { theme: "standard-notes", title: "Standard Notes", repo: "standard-notes", icon: "/icons/used/pack-7/016-eyeball.svg", platform: ["all"] } },
  { params: { theme: "starship", title: "Starship", repo: "starship", icon: "/icons/used/pack-8/041-spaceship.svg", platform: ["all"] } },
  { params: { theme: "steam", title: "Steam", repo: "steam", icon: "/icons/used/pack-5/049-target.svg", platform: ["all"] } },
  { params: { theme: "streamlit", title: "Streamlit", repo: "streamlit", icon: "/icons/used/pack-10/025-monster.svg", platform: ["all"] } },
  { params: { theme: "sublime", title: "Sublime", repo: "sublime", icon: "/icons/used/pack-1/044-spider-web.svg", platform: ["all"] } },
  { params: { theme: "suckless-tabbed", title: "Suckless Tabbed", repo: "suckless-tabbed", icon: "/icons/used/pack-9/007-zombie.svg", platform: ["all"] } },
  { params: { theme: "sumatra-pdf", title: "Sumatra PDF", repo: "sumatra-pdf", icon: "/icons/used/pack-10/013-frankenstein.svg", platform: ["windows"] } },
  { params: { theme: "swaylock", title: "Swaylock", repo: "swaylock", icon: "/icons/used/pack-2/027-shield.svg", platform: ["linux"] } },
  { params: { theme: "swiftui", title: "SwiftUI", repo: "swiftui", icon: "/icons/used/pack-10/031-wizard-1.svg", platform: ["mac"] } },
  { params: { theme: "tabletop-simulator", title: "Tabletop Simulator", repo: "tabletop-simulator", icon: "/icons/used/pack-2/048-cards.svg", platform: ["all"] } },
  { params: { theme: "tailwind", title: "Tailwind", repo: "tailwind", icon: "/icons/used/pack-10/034-moon.svg", platform: ["all"] } },
  { params: { theme: "telegram-android", title: "Telegram Android", repo: "telegram-android", icon: "/icons/used/pack-6/038-skull.svg", platform: ["all"] } },
  { params: { theme: "telegram-ios", title: "Telegram iOS", repo: "telegram-ios", icon: "/icons/used/pack-7/006-skeleton.svg", platform: ["mac"] } },
  { params: { theme: "telegram", title: "Telegram", repo: "telegram", icon: "/icons/used/pack-4/036-hermes-1.svg", platform: ["all"] } },
  { params: { theme: "terminal", title: "Terminal.app", repo: "terminal-app", icon: "/icons/used/pack-1/035-cauldron.svg", platform: ["mac"] } },
  { params: { theme: "terminator", title: "Terminator", repo: "terminator", icon: "/icons/used/pack-7/003-werewolf.svg", platform: ["linux", "mac"] } },
  { params: { theme: "termite", title: "Termite", repo: "termite", icon: "/icons/used/pack-3/037-voodoo-doll.svg", platform: ["linux"] } },
  { params: { theme: "termux", title: "Termux", repo: "termux", icon: "/icons/used/pack-7/022-mummy.svg", platform: ["all"] } },
  { params: { theme: "texshop", title: "TeXShop", repo: "texshop", icon: "/icons/used/pack-9/022-ghost.svg", platform: ["mac"] } },
  { params: { theme: "texstudio", title: "TeXstudio", repo: "texstudio", icon: "/icons/used/pack-10/045-jack-o-lantern.svg", platform: ["all"] } },
  { params: { theme: "textastic", title: "Textastic", repo: "textastic", icon: "/icons/used/pack-9/006-frankenstein.svg", platform: ["mac"] } },
  { params: { theme: "textmate", title: "Textmate", repo: "textmate", icon: "/icons/used/pack-1/038-tombstone.svg", platform: ["mac"] } },
  { params: { theme: "textual", title: "Textual", repo: "textual", icon: "/icons/used/pack-1/032-bat.svg", platform: ["mac"] } },
  { params: { theme: "thelounge", title: "The Lounge", repo: "thelounge", icon: "/icons/used/pack-7/012-dead-tree.svg", platform: ["all"] } },
  { params: { theme: "thonny", title: "Thonny", repo: "thonny", icon: "/icons/used/pack-4/042-hydra.svg", platform: ["all"] } },
  { params: { theme: "thunderbird", title: "Thunderbird", repo: "thunderbird", icon: "/icons/used/pack-4/003-phoenix.svg", platform: ["all"] } },
  { params: { theme: "tiddlywiki", title: "TiddlyWiki", repo: "tiddlywiki", icon: "/icons/used/pack-5/035-tent.svg", platform: ["all"] } },
  { params: { theme: "tig", title: "tig", repo: "tig", icon: "/icons/used/pack-10/011-cauldron.svg", platform: ["all"] } },
  { params: { theme: "tilix", title: "Tilix", repo: "tilix", icon: "/icons/used/pack-2/046-ghost.svg", platform: ["linux"] } },
  { params: { theme: "tint2", title: "tint2", repo: "tint2", icon: "/icons/used/pack-5/009-potion.svg", platform: ["linux"] } },
  { params: { theme: "tmux", title: "tmux", repo: "tmux", icon: "/icons/used/pack-1/030-clown.svg", platform: ["linux", "mac"] } },
  { params: { theme: "todoist", title: "Todoist", repo: "todoist", icon: "/icons/used/pack-4/004-hephaestus.svg", platform: ["all"] } },
  { params: { theme: "total-commander", title: "Total Commander", repo: "total-commander", icon: "/icons/used/pack-3/044-spell-1.svg", platform: ["windows"] } },
  { params: { theme: "tower", title: "Tower", repo: "tower", icon: "/icons/used/pack-8/025-observatory.svg", platform: ["mac", "window"] } },
  { params: { theme: "tridactyl", title: "Tridactyl", repo: "tridactyl", icon: "/icons/used/pack-1/021-candy-corn.svg", platform: ["all"] } },
  { params: { theme: "tty", title: "TTY", repo: "tty", icon: "/icons/used/pack-10/023-living-dead.svg", platform: ["linux"] } },
  { params: { theme: "tym", title: "tym", repo: "tym", icon: "/icons/used/pack-9/002-crow.svg", platform: ["linux"] } },
  { params: { theme: "typora", title: "Typora", repo: "typora", icon: "/icons/used/pack-1/017-witch-1.svg", platform: ["all"] } },
  { params: { theme: "ueli", title: "Ueli", repo: "ueli", icon: "/icons/used/pack-9/042-eye.svg", platform: ["mac", "windows"] } },
  { params: { theme: "ulauncher", title: "Ulauncher", repo: "ulauncher", icon: "/icons/used/pack-7/005-candies.svg", platform: ["linux"] } },
  { params: { theme: "ulysses", title: "Ulysses", repo: "ulysses", icon: "/icons/used/pack-3/027-magician-hat-1.svg", platform: ["mac"] } },
  { params: { theme: "unigram", title: "Unigram", repo: "unigram", icon: "/icons/used/pack-7/040-jack-o-lantern.svg", platform: ["windows"] } },
  { params: { theme: "unreal-engine", title: "Unreal Engine", repo: "unreal-engine", icon: "/icons/used/pack-9/017-fangs.svg", platform: ["all"] } },
  { params: { theme: "uptime-kuma", title: "Uptime Kuma", repo: "uptime-kuma", icon: "/icons/used/pack-10/036-werewolf.svg", platform: ["all"] } },
  { params: { theme: "vim", title: "Vim", repo: "vim", icon: "/icons/used/pack-1/040-zombie-1.svg", platform: ["all"], synonyms: ["neovim", "gvim"] } },
  { params: { theme: "vimium", title: "Vimium", repo: "vimium", icon: "/icons/used/pack-3/013-chest-1.svg", platform: ["all"] } },
  { params: { theme: "vis", title: "vis", repo: "vis", icon: "/icons/used/pack-13/009-pumpkin.svg", platform: ["linux"] } },
  { params: { theme: "visual-basic", title: "Visual Basic 6", repo: "visual-basic-6", icon: "/icons/used/pack-3/024-magic-wand.svg", platform: ["windows"] } },
  { params: { theme: "visual-spigot", title: "Visual Spigot", repo: "visual-spigot", icon: "/icons/used/pack-10/018-owl.svg", platform: ["windows"] } },
  { params: { theme: "visual-studio-code", title: "Visual Studio Code", repo: "visual-studio-code", icon: "/icons/used/pack-1/048-frankenstein.svg", platform: ["all"], synonyms: ["vscode"] } },
  { params: { theme: "visual-studio", title: "Visual Studio", repo: "visual-studio", icon: "/icons/used/pack-1/041-skeleton.svg", platform: ["all"] } },
  { params: { theme: "vital", title: "Vital", repo: "vital", icon: "/icons/used/pack-4/049-lyre.svg", platform: ["all"] } },
  { params: { theme: "vivado", title: "Vivado", repo: "vivado", icon: "/icons/used/pack-8/002-satellite.svg", platform: ["linux", "windows"] } },
  { params: { theme: "vivaldi", title: "Vivaldi", repo: "vivaldi", icon: "/icons/used/pack-1/003-broom.svg", platform: ["all"] } },
  { params: { theme: "vortex-mod-manager", title: "Vortex Mod Manager", repo: "vortex-mod-manager", icon: "/icons/used/pack-2/011-game-controller.svg", platform: ["windows"] } },
  { params: { theme: "wallpaper", title: "Wallpaper", repo: "wallpaper", icon: "/icons/used/pack-5/034-skull.svg", platform: ["all"] } },
  { params: { theme: "warp", title: "Warp", repo: "warp", icon: "/icons/used/pack-10/003-haunted-house.svg", platform: ["mac"] } },
  { params: { theme: "waybar", title: "Waybar", repo: "waybar", icon: "/icons/used/pack-5/031-magic cape.svg", platform: ["linux"] } },
  { params: { theme: "wezterm", title: "WezTerm", repo: "wezterm", icon: "/icons/used/pack-5/040-ticket.svg", platform: ["all"] } },
  { params: { theme: "windows-terminal", title: "Windows Terminal", repo: "windows-terminal", icon: "/icons/used/pack-3/047-tube.svg", platform: ["windows"] } },
  { params: { theme: "windterm", title: "WindTerm", repo: "windterm", icon: "/icons/used/pack-9/015-finger.svg", platform: ["all"] } },
  { params: { theme: "wing", title: "Wing", repo: "wing", icon: "/icons/used/pack-3/043-snake.svg", platform: ["all"] } },
  { params: { theme: "wofi", title: "wofi", repo: "wofi", icon: "/icons/used/pack-7/050-poison.svg", platform: ["linux"] } },
  { params: { theme: "wolfram-notebooks", title: "Wolfram Notebooks", repo: "wolfram-notebooks", icon: "/icons/used/pack-3/002-spellbook.svg", platform: ["all"] } },
  { params: { theme: "wordpress", title: "Wordpress", repo: "wordpress", icon: "/icons/used/pack-5/004-tarot.svg", platform: ["all"] } },
  { params: { theme: "wox", title: "Wox", repo: "wox", icon: "/icons/used/pack-5/003-crystal ball.svg", platform: ["windows"] } },
  { params: { theme: "wp", title: "WP", repo: "wp", icon: "/icons/used/pack-4/028-column.svg", platform: ["all"] } },
  { params: { theme: "xchat", title: "XChat", repo: "xchat", icon: "/icons/used/pack-6/001-coffin.svg", platform: ["linux", "windows"] } },
  { params: { theme: "xcode", title: "Xcode", repo: "xcode", icon: "/icons/used/pack-3/048-unicorn.svg", platform: ["mac"] } },
  { params: { theme: "xfce4-terminal", title: "Xfce4 Terminal", repo: "xfce4-terminal", icon: "/icons/used/pack-7/029-clown.svg", platform: ["linux"] } },
  { params: { theme: "xournalpp", title: "Xournal++", repo: "xournalpp", icon: "/icons/used/pack-7/013-witch.svg", platform: ["all"] } },
  { params: { theme: "xresources", title: "Xresources", repo: "xresources", icon: "/icons/used/pack-5/047-mortar.svg", platform: ["all"] } },
  { params: { theme: "yakuake", title: "Yakuake", repo: "yakuake", icon: "/icons/used/pack-9/039-gift.svg", platform: ["all"] } },
  { params: { theme: "youtube-music-desktop", title: "YouTube Music Desktop", repo: "youtube-music-desktop", icon: "/icons/used/pack-6/044-violin.svg", platform: ["all"] } },
  { params: { theme: "youtube", title: "Youtube", repo: "youtube", icon: "/icons/used/pack-9/005-dracula.svg", platform: ["all"] } },
  { params: { theme: "yunohost", title: "YunoHost", repo: "yunohost", icon: "/icons/used/pack-5/014-scroll.svg", platform: ["all"] } },
  { params: { theme: "zathura", title: "Zathura", repo: "zathura", icon: "/icons/used/pack-6/035-grave.svg", platform: ["all"] } },
  { params: { theme: "zellij", title: "Zellij", repo: "zellij", icon: "/icons/used/pack-3/004-broom.svg", platform: ["linux", "mac"] } },
  { params: { theme: "zsh-syntax-highlighting", title: "zsh-syntax-highlighting", repo: "zsh-syntax-highlighting", icon: "/icons/used/pack-10/020-reaper.svg", platform: ["all"] } },
  { params: { theme: "zsh", title: "Zsh", repo: "zsh", icon: "/icons/used/pack-1/034-eye.svg", platform: ["all"] } },
];

export default paths;
